### ISSUE TITLE
Examples for NMAP Scanner need updating

### ISSUE THREAD

**Issue by 3thmanE-Al-Hayek** [PacktPublishing/Hands-On-Penetration-Testing-with-Python#1]
I am on Chapter 5 and 6 at the moment. I cannot complete the creation of the NMAP scanner because I cannot access the links to the code or the VM. The screenshots of the code are not enough to go by to recreate the full scanner. Please ask the author to update the links or send a working link to the VM/Github code. Any links to his Github send you to a 404 page (I presume he has deleted the code).

**Comment by FurqanKhan1** [comment]
Dear user ,

Can you please share the links that you are trying.


Kind regards

**Comment by 3thmanE-Al-Hayek** [comment]
Thanks for the fast reply. 

Here is a link to the Kali VM image you mention (page 142): https://drive-google-com.passerelle.univ-rennes1.fr/file/d/1e0Wwc1r_7XtL0uCLJXeLstMgJR68wNLF/view?usp=sharing

Here is a link to the code you say is hosted in one of your Github repos (page 143): https://github.com/FurqanKhan1/Dictator/blob/master/Dictator_service/Driver_main_class.py

**Comment by FurqanKhan1** [comment]
Dear user ,

Please allow me sometime. I shall share the updated link of vm with you
,and will republish the code to github. Basically the repo was moved to
bitbucket.


However i shall update you in sometime.

@packet ,guys can we put an update in the ebook ,for the kali linux vm
link.


Kind regards

**Comment by 3thmanE-Al-Hayek** [comment]
Thank you!

**Comment by FurqanKhan1** [comment]
Dear User

Pardon me for the delay. I have been occupied off late.

Please find the link to download the VM  :
https://drive.google.com/file/d/1e0Wwc1r_7XtL0uCLJXeLstMgJR68wNLF/view?usp=drivesdk

Additionally , you can access the code base from GitHub.

Please note , the book has a mistake for the username to access the VM. The
username is root not PTO_root.

Kind regards

**Comment by 3thmanE-Al-Hayek** [comment]
No problem, thank you!
