### ISSUE TITLE
VM password is incorrect in your book

### ISSUE THREAD

**Issue by fin3ss3g0d** [PacktPublishing/Hands-On-Penetration-Testing-with-Python#2]
The lines that you provided in your book: "Alternatively, I have created a plug-and-play Kali VM image, which has got all the prerequisite installations and the code base out of the box.  This can be downloaded and executed hassle-free from the URL <https://drive.google.com/file/d/1e0Wwc1r_7XtL0uCLJXeLstMgJR68wNLF/view?usp=sharing>.  The default username is:PTO_root and the password is: PTO_root"  I paid for your book through Amazon and this has been an awful experience getting your code base for the book.  I finally get to Github and you still can't upload the files here, I still have to download your VM.  And even after downloading your VM, the username and password "PTO_root" are incorrect.  How am I supposed to get the code for the book?  I am thinking about returning the book and getting my money back.  This is RIDICULOUS.  At least put the correct password and username for the VM in the book, what is the matter with you?

**Comment by FurqanKhan1** [comment]
Dear user


Please find the link to download the VM  :
https://drive.google.com/file/d/1e0Wwc1r_7XtL0uCLJXeLstMgJR68wNLF/view?usp=drivesdk

Additionally , you can access the code base from GitHub.

Please note , the book has a mistake for the username to access the VM. The
username is root not PTO_root

About github repo ,its a private repo so one cant upload files. You can
clone and upload at your branch

**Comment by fin3ss3g0d** [comment]
Hey, I got into the VM working properly, thank you very much.  Chapters 5 & 6 were the main reasons I bought the book and they weren't on Github so I needed the VM.  Appreciate the timely response and I can't wait to finish the book.
